service_hostname: localhost
parallel_mode: thread
feeds:
    camera_1:
        backend: 'opencv'
        debug: true

        capture:
            type: 'rtsp'
            path: 'rtsp://admin:adminadmin@192.168.1.122:554/h265Preview_01_main'
            fps: 15

        web:
            enabled: false
            resolution: [640, 480]
            fps: 5

        mqtt:
            enabled: true
            broker_host: 'mqtt-server'
            broker_port: 1883
            topic: 'camera_presence/camera_1/feed'

        write_to_disk:
            enabled: true
            path: '/workspace/output_images/'
